# utils.py
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import io

def bias_bar_chart(bias_before, bias_after):
    fig, ax = plt.subplots(figsize=(5, 3))
    bars = ax.bar(
        ['Before Fairness', 'After Fairness'],
        [bias_before, bias_after],
        color=['#e74c3c', '#2ecc71'],
        width=0.4
    )
    ax.set_ylabel('Demographic Parity Difference')
    ax.set_title('Bias Score Comparison')
    ax.set_ylim(0, 1)
    for bar, val in zip(bars, [bias_before, bias_after]):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
                f'{val:.3f}', ha='center', fontweight='bold')
    plt.tight_layout()
    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=120)
    buf.seek(0)
    plt.close()
    return buf


def shap_bar_chart(shap_values, feature_names):
    import numpy as np
    fig, ax = plt.subplots(figsize=(6, 3))

    vals = np.array(shap_values)
    if vals.ndim == 2:
        vals = vals[0]

    colors = ['#3498db' if v > 0 else '#e74c3c' for v in vals]
    bars = ax.barh(feature_names, vals, color=colors)
    ax.set_xlabel('SHAP Value (Impact on Decision)')
    ax.set_title('Why was this decision made?')
    ax.axvline(x=0, color='black', linewidth=0.8)

    for bar, val in zip(bars, vals):
        ax.text(val + 0.001, bar.get_y() + bar.get_height()/2,
                f'{val:.3f}', va='center', fontsize=9)

    plt.tight_layout()
    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=120)
    buf.seek(0)
    plt.close()
    return buf


def generate_pdf_report(candidate_data, pred_fair, prob_biased, bias_flag):
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 15, 'Fair Hiring AI - Candidate Report', ln=True, align='C')
    pdf.ln(5)

    # Divider
    pdf.set_draw_color(100, 100, 255)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)

    # Decision
    pdf.set_font('Helvetica', 'B', 14)
    result_text = 'SELECTED' if pred_fair == 1 else 'NOT SELECTED'
    color = (39, 174, 96) if pred_fair == 1 else (231, 76, 60)
    pdf.set_text_color(*color)
    pdf.cell(0, 10, f'Decision: {result_text}', ln=True)
    pdf.set_text_color(30, 30, 30)
    pdf.ln(3)

    # Confidence
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 7, f'Confidence: {prob_biased*100:.1f}%', ln=True)
    pdf.ln(5)

    # Candidate Details
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'Candidate Details:', ln=True)
    pdf.set_font('Helvetica', '', 11)
    for key, val in candidate_data.items():
        pdf.cell(0, 7, f'  {key}: {val}', ln=True)
    pdf.ln(5)

    # Fairness Report
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'Fairness Report:', ln=True)
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 7, f'  {bias_flag}', ln=True)
    pdf.cell(0, 7, '  [OK] Decision based on skills and merit', ln=True)
    pdf.cell(0, 7, '  [OK] Fairlearn bias mitigation applied', ln=True)
    pdf.ln(8)

    # Footer
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.4)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, 'Generated by Fair Hiring AI System', ln=True, align='C')

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf